// Checkout-sync gRPC contract (epic:checkout-sync, sty_7ece3dc3).
//
// Canonical definition of service Sync. satelle-server copies this proto
// verbatim (same posture as testdata/openapi.yaml) and implements it. This
// repo publishes the contract; it does not implement the server.
//
// Subscribe is deliberately out of scope (a later story). Do not add it here.
// There is no gRPC login — OAuth stays on HTTP /oauth/*.
//
// record fields carry UTF-8 JSON (the opaque CLI work-item / ledger payload);
// the server may promote fields from them, matching REST json.RawMessage.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: checkout_sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Items         []*WorkItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Ledger        []*LedgerEntry         `protobuf:"bytes,3,rep,name=ledger,proto3" json:"ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_checkout_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_checkout_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ApplyRequest) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ApplyRequest) GetLedger() []*LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         int32                  `protobuf:"varint,1,opt,name=items,proto3" json:"items,omitempty"`
	Ledger        int32                  `protobuf:"varint,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_checkout_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_checkout_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetItems() int32 {
	if x != nil {
		return x.Items
	}
	return 0
}

func (x *ApplyResponse) GetLedger() int32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // optional filter; mirrors REST ListWorkstateItems
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_checkout_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_checkout_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SnapshotRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WorkItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Ledger        []*LedgerEntry         `protobuf:"bytes,2,rep,name=ledger,proto3" json:"ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_checkout_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_checkout_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotResponse) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SnapshotResponse) GetLedger() []*LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

type WorkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Origin        string                 `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	Record        []byte                 `protobuf:"bytes,7,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_checkout_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_checkout_sync_proto_rawDescGZIP(), []int{4}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkItem) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *WorkItem) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Record        []byte                 `protobuf:"bytes,6,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_checkout_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_checkout_sync_proto_rawDescGZIP(), []int{5}
}

func (x *LedgerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerEntry) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *LedgerEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LedgerEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerEntry) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *LedgerEntry) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_checkout_sync_proto protoreflect.FileDescriptor

const file_checkout_sync_proto_rawDesc = "" +
	"\n" +
	"\x13checkout_sync.proto\x12\x0fsatelle.sync.v1\"\x8f\x01\n" +
	"\fApplyRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.satelle.sync.v1.WorkItemR\x05items\x124\n" +
	"\x06ledger\x18\x03 \x03(\v2\x1c.satelle.sync.v1.LedgerEntryR\x06ledger\"=\n" +
	"\rApplyResponse\x12\x14\n" +
	"\x05items\x18\x01 \x01(\x05R\x05items\x12\x16\n" +
	"\x06ledger\x18\x02 \x01(\x05R\x06ledger\"?\n" +
	"\x0fSnapshotRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"y\n" +
	"\x10SnapshotResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.satelle.sync.v1.WorkItemR\x05items\x124\n" +
	"\x06ledger\x18\x02 \x03(\v2\x1c.satelle.sync.v1.LedgerEntryR\x06ledger\"\xa0\x01\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\x12\x16\n" +
	"\x06record\x18\a \x01(\fR\x06record\"\x90\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12\x16\n" +
	"\x06record\x18\x06 \x01(\fR\x06record2\x9f\x01\n" +
	"\x04Sync\x12F\n" +
	"\x05Apply\x12\x1d.satelle.sync.v1.ApplyRequest\x1a\x1e.satelle.sync.v1.ApplyResponse\x12O\n" +
	"\bSnapshot\x12 .satelle.sync.v1.SnapshotRequest\x1a!.satelle.sync.v1.SnapshotResponseB\xbc\x01\n" +
	"\x13com.satelle.sync.v1B\x11CheckoutSyncProtoP\x01Z4github.com/bobmcallan/satelle/internal/hosted/syncpb\xa2\x02\x03SSX\xaa\x02\x0fSatelle.Sync.V1\xca\x02\x0fSatelle\\Sync\\V1\xe2\x02\x1bSatelle\\Sync\\V1\\GPBMetadata\xea\x02\x11Satelle::Sync::V1b\x06proto3"

var (
	file_checkout_sync_proto_rawDescOnce sync.Once
	file_checkout_sync_proto_rawDescData []byte
)

func file_checkout_sync_proto_rawDescGZIP() []byte {
	file_checkout_sync_proto_rawDescOnce.Do(func() {
		file_checkout_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_sync_proto_rawDesc), len(file_checkout_sync_proto_rawDesc)))
	})
	return file_checkout_sync_proto_rawDescData
}

var file_checkout_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_checkout_sync_proto_goTypes = []any{
	(*ApplyRequest)(nil),     // 0: satelle.sync.v1.ApplyRequest
	(*ApplyResponse)(nil),    // 1: satelle.sync.v1.ApplyResponse
	(*SnapshotRequest)(nil),  // 2: satelle.sync.v1.SnapshotRequest
	(*SnapshotResponse)(nil), // 3: satelle.sync.v1.SnapshotResponse
	(*WorkItem)(nil),         // 4: satelle.sync.v1.WorkItem
	(*LedgerEntry)(nil),      // 5: satelle.sync.v1.LedgerEntry
}
var file_checkout_sync_proto_depIdxs = []int32{
	4, // 0: satelle.sync.v1.ApplyRequest.items:type_name -> satelle.sync.v1.WorkItem
	5, // 1: satelle.sync.v1.ApplyRequest.ledger:type_name -> satelle.sync.v1.LedgerEntry
	4, // 2: satelle.sync.v1.SnapshotResponse.items:type_name -> satelle.sync.v1.WorkItem
	5, // 3: satelle.sync.v1.SnapshotResponse.ledger:type_name -> satelle.sync.v1.LedgerEntry
	0, // 4: satelle.sync.v1.Sync.Apply:input_type -> satelle.sync.v1.ApplyRequest
	2, // 5: satelle.sync.v1.Sync.Snapshot:input_type -> satelle.sync.v1.SnapshotRequest
	1, // 6: satelle.sync.v1.Sync.Apply:output_type -> satelle.sync.v1.ApplyResponse
	3, // 7: satelle.sync.v1.Sync.Snapshot:output_type -> satelle.sync.v1.SnapshotResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_checkout_sync_proto_init() }
func file_checkout_sync_proto_init() {
	if File_checkout_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_sync_proto_rawDesc), len(file_checkout_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_sync_proto_goTypes,
		DependencyIndexes: file_checkout_sync_proto_depIdxs,
		MessageInfos:      file_checkout_sync_proto_msgTypes,
	}.Build()
	File_checkout_sync_proto = out.File
	file_checkout_sync_proto_goTypes = nil
	file_checkout_sync_proto_depIdxs = nil
}
