package subsync

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// skipIfModesAreAdvisory guards the permission tests: 0o444 denies nobody when
// the test runs as root, and Windows permission semantics differ entirely.
func skipIfModesAreAdvisory(t *testing.T) {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("POSIX file modes only")
	}
	if os.Geteuid() == 0 {
		t.Skip("running as root — 0o444 denies nothing")
	}
}

// TestRestoreReadOnlyDestinationDoesNotAbortBatch is the regression for
// sty_4c3729e7: a destination at 0o444 used to make Restore return on the first
// file, which left the documents cursor unsaved and re-failed identically on
// every later pull — a permanent wedge. The batch must complete.
//
// Against the pre-fix Restore this fails twice over: it returns an error, and
// the file ordered after the read-only one is never written.
func TestRestoreReadOnlyDestinationDoesNotAbortBatch(t *testing.T) {
	skipIfModesAreAdvisory(t)
	dataDir := t.TempDir()

	// A generated view, as the OKF materializer leaves it: read-only on disk.
	roDir := filepath.Join(dataDir, "documents", "story-implementation-summary")
	if err := os.MkdirAll(roDir, 0o755); err != nil {
		t.Fatal(err)
	}
	roPath := filepath.Join(roDir, "commit-summary.md")
	if err := os.WriteFile(roPath, []byte("old generated bytes\n"), 0o444); err != nil {
		t.Fatal(err)
	}
	// An ordinary writable document, ordered AFTER the read-only one so an
	// aborting batch would leave it untouched.
	rwPath := filepath.Join(dataDir, "documents", "notes.md")
	if err := os.WriteFile(rwPath, []byte("old\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	files := []File{
		{Path: "documents/story-implementation-summary/commit-summary.md", Content: []byte("---\ngenerated: satelle\n---\nnew generated bytes\n")},
		{Path: "documents/notes.md", Content: []byte("new\n")},
		{Path: "logs/server.log", Content: []byte("policy-excluded")},
	}
	res, err := Restore(dataDir, files)
	if err != nil {
		t.Fatalf("Restore must not abort the batch on a read-only destination: %v", err)
	}
	if res.Written != 2 {
		t.Errorf("Written = %d, want 2", res.Written)
	}
	if len(res.Skipped) != 1 || res.Skipped[0] != "logs/server.log" {
		t.Errorf("Skipped = %v, want the policy-excluded log only", res.Skipped)
	}
	if len(res.Failed) != 0 {
		t.Errorf("Failed = %v, want none — a read-only destination is satelle's own marker, not a failure", res.Failed)
	}
	if got, _ := os.ReadFile(rwPath); string(got) != "new\n" {
		t.Errorf("the file after the read-only one was not written: %q", got)
	}
	if got, _ := os.ReadFile(roPath); string(got) != "---\ngenerated: satelle\n---\nnew generated bytes\n" {
		t.Errorf("read-only generated view not updated: %q", got)
	}
	if fi, err := os.Stat(roPath); err != nil || fi.Mode().Perm() != 0o444 {
		t.Errorf("generated view must stay 0o444, got %v (err %v)", fi.Mode().Perm(), err)
	}
}

// TestRestoreReportsUnwritableWithoutAborting proves the genuinely unrecoverable
// case is REPORTED rather than swallowed or fatal: the file lands in
// Result.Failed, the rest of the batch still completes, and Failed stays
// distinct from Skipped — one is a filesystem condition, the other is policy.
func TestRestoreReportsUnwritableWithoutAborting(t *testing.T) {
	skipIfModesAreAdvisory(t)
	dataDir := t.TempDir()

	// A directory that cannot be written into: the remove-then-write cannot
	// rescue a file inside it.
	lockedDir := filepath.Join(dataDir, "documents", "locked")
	if err := os.MkdirAll(lockedDir, 0o755); err != nil {
		t.Fatal(err)
	}
	stuck := filepath.Join(lockedDir, "stuck.md")
	if err := os.WriteFile(stuck, []byte("original\n"), 0o444); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(lockedDir, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(lockedDir, 0o755) }) // so TempDir teardown works

	files := []File{
		{Path: "documents/locked/stuck.md", Content: []byte("replacement\n")},
		{Path: "documents/fine.md", Content: []byte("written anyway\n")},
	}
	res, err := Restore(dataDir, files)
	if err != nil {
		t.Fatalf("an unwritable file must not be a fatal error: %v", err)
	}
	if len(res.Failed) != 1 || res.Failed[0].Path != "documents/locked/stuck.md" {
		t.Fatalf("Failed = %v, want the one unwritable path", res.Failed)
	}
	if res.Failed[0].Err == nil {
		t.Error("a failure must carry its reason")
	}
	if len(res.Skipped) != 0 {
		t.Errorf("Skipped = %v — a filesystem failure must never be reported as a policy skip", res.Skipped)
	}
	if res.Written != 1 {
		t.Errorf("Written = %d, want the sibling file still written", res.Written)
	}
	if got, _ := os.ReadFile(stuck); string(got) != "original\n" {
		t.Errorf("unwritable file changed: %q", got)
	}
	// Callers for whom a partial restore is a failure get one joined error.
	if res.Err() == nil {
		t.Error("Result.Err() must surface the failures for callers that fail loudly")
	}
}

// TestRestorePreservesAndSetsMode proves mode is right end to end: an existing
// writable file stays writable, a NEW generated view is created read-only (today
// it would land 0o644 and silently lose its protection), and an existing
// read-only generated view stays read-only across a rewrite.
func TestRestorePreservesAndSetsMode(t *testing.T) {
	skipIfModesAreAdvisory(t)
	dataDir := t.TempDir()

	existing := filepath.Join(dataDir, "documents", "plain.md")
	if err := os.MkdirAll(filepath.Dir(existing), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(existing, []byte("before\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldView := filepath.Join(dataDir, "documents", "old-view.md")
	if err := os.WriteFile(oldView, []byte("---\ngenerated: satelle\n---\nbefore\n"), 0o444); err != nil {
		t.Fatal(err)
	}

	generated := []byte("---\ngenerated: satelle\nname: x\n---\nfresh\n")
	res, err := Restore(dataDir, []File{
		{Path: "documents/plain.md", Content: []byte("after\n")},
		{Path: "documents/new-view.md", Content: generated},
		{Path: "documents/old-view.md", Content: generated},
	})
	if err != nil || res.Written != 3 {
		t.Fatalf("Restore = %+v, err %v", res, err)
	}

	for _, tc := range []struct {
		path string
		want os.FileMode
		why  string
	}{
		{existing, 0o644, "an ordinary document restored over a writable file stays writable"},
		{filepath.Join(dataDir, "documents", "new-view.md"), 0o444, "a NEW generated view must be created read-only, not 0o644"},
		{oldView, 0o444, "a rewritten generated view keeps its read-only protection"},
	} {
		fi, err := os.Stat(tc.path)
		if err != nil {
			t.Fatalf("stat %s: %v", tc.path, err)
		}
		if fi.Mode().Perm() != tc.want {
			t.Errorf("%s: mode %v, want %v — %s", filepath.Base(tc.path), fi.Mode().Perm(), tc.want, tc.why)
		}
	}
	if got, _ := os.ReadFile(oldView); string(got) != string(generated) {
		t.Errorf("generated view content not updated: %q", got)
	}
}

// TestIsGeneratedMarker pins the marker scan: only a leading frontmatter block
// with `generated: satelle` counts. The spelling is owned by internal/docindex.
func TestIsGeneratedMarker(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{"marker in frontmatter", "---\ngenerated: satelle\nname: x\n---\nbody\n", true},
		{"marker with spacing", "---\nname: x\ngenerated:   satelle\n---\nbody\n", true},
		{"no frontmatter", "generated: satelle\n", false},
		{"different generator", "---\ngenerated: someone-else\n---\nbody\n", false},
		{"marker only in body", "---\nname: x\n---\ngenerated: satelle\n", false},
		{"unterminated frontmatter", "---\ngenerated: satelle\n", false},
		{"empty", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := isGenerated([]byte(tc.content)); got != tc.want {
				t.Fatalf("isGenerated = %v, want %v", got, tc.want)
			}
		})
	}
}
